# pvc.yaml

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gitlab-runner.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
